In [38]:
import os
os.getcwd() #TO show current working directory
#os.makedirs("C:\\myfolder") #to create a new folder
#os.listdir('C:/Users/Adinath/Desktop/Data_Science')# to check all content present in directory
#os.chdir('D:\\myfolder')  #Change the working directory
#os.rename('oldfile.txt', 'newfile.txt')

'C:\\Users\\Adinath\\Desktop\\Data_Science'

Working with TXT document

reading from a file

In [57]:
#IO is a built in module in python which provides file handling operations
import io
f1 = open('C:/Users/Adinath/Desktop/Data_Science/akshay.txt', 'r')
f1.read() #read full conetnt of file
f1.readline() #Read single line
f1.close()

In [60]:
#to read all contents of file by liene by line
f1 = open('C:/Users/Adinath/Desktop/Data_Science/akshay.txt', 'r')
for line in f1:
    print(line)
f1.close()    

this is first line

this is second line

i am akshay

hcl


Writing to a file

In [71]:
newfile = open('C:/Users/Adinath/Desktop/Data_Science/akshay123.txt', mode='w', encoding='utf-8')
newfile.write('i am working as a software engineer \n')
newfile.write('i am working in DFS project \n')
newfile.write('HCL ia a MNC company \n')
newfile.close()

In [72]:
newfile = open('C:/Users/Adinath/Desktop/Data_Science/akshay123.txt', 'r')
for line in newfile:
    print(line)
newfile.close() 

i am working as a software engineer 

i am working in DFS project 

HCL ia a MNC company 



In [74]:
# How to write to file number of lines ata once
list = ['i am a good boy \n', 'my home is jamkhandi \n', 'i stay in bnaglaore \n']
newfile = open('C:/Users/Adinath/Desktop/Data_Science/akshay123.txt', mode='a+', encoding='utf-8')
newfile.writelines(list)
newfile.read()

''

In [75]:
newfile = open('C:/Users/Adinath/Desktop/Data_Science/akshay123.txt', 'r')
for line in newfile:
    print(line)
newfile.close() 

i am working as a software engineer 

i am working in DFS project 

HCL ia a MNC company 

i am a good boy 

my home is jamkhandi 

i stay in bnaglaore 

i am a good boy 

my home is jamkhandi 

i stay in bnaglaore 



Working with Microsoft Word document

In [95]:
#We use module called 'docx' to work with mocrosoft word documents

#create instance of word documenrt
import docx
document = docx.Document() #to create instance 'document' we are invoking method 'Document'

#add heading to the document
document.add_heading('this is a level 0 heading', 0)

#add paragraph to the word document
document.add_paragraph('this is paragraph')
doc.add_heading('p1')
doc.add_heading('p2')
doc.add_heading('p3')
#Add pagebreak to the document
document.add_page_break()

#save tyhe document
document.save('document.docx')  #Now the document.txt file is created

In [98]:
from docx import Document

doc = docx.Document('document.docx')

print('Printing whole contents of documents \n')
for para in doc.paragraphs:
    print(para.text)

Printing whole contents of documents 

this is a level 0 heading
this is paragraph




In [244]:
print('hi')
print("hi")
print('''hi''')
print("""hi""")

hi
hi
hi
hi


In [16]:
str = 'Hello World!' 
print (str)          # Prints complete string 
print (str[0])       # Prints first character of the string 
print (str[2:5])     # Prints characters starting from 3rd to 5th 
print (str[2:])      # Prints string starting from 3rd character 
print (str * 2)      # Prints string two times 
print (str + "TEST") # Prints concatenated string 

Hello World!
H
llo
llo World!
Hello World!Hello World!
Hello World!TEST


In [112]:
x = "Hello's world"
print(x)
#we have to use escape charecter '\' when using a single charecter inside single charecter & Double charecter inside DOuble charecter
y = 'Hello\'s world'
print(y)
z = "Hello\"s world"
print(z)

Hello's world
Hello's world
Hello"s world


In [118]:
x = 'akshaykumar'
print(x[0:6])
print(x[0:6] * 5) #Prints akshay 100times

akshay
akshayakshayakshayakshayakshay


In [167]:
a = [0,1,2,3,4,5,6,7,8,9,10]
print(a)
print(a[0:5]) #prints elements starting from 0 index to till 5 index
print(a[0:8:2]) #prints elements starting from 0 index to till 5 index, and 2 interval numbers
print(a[0:11:4]) #prints elements starting from 0 index to till 5 index, and 4 interval numbers
#OR
print(a[::4]) #prints elements starting from 0 index to till 5 index, and 4 interval numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 2, 3, 4]
[0, 2, 4, 6]
[0, 4, 8]
[0, 4, 8]


In [176]:
# TO get all the numbers in reverse in list
a = [0,1,2,3,4,5,6,7,8,9,10]
print(a)
print(' \nreverse order list is:-')
print(a[::-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
 
reverse order list is:-
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [235]:
import datetime
a = datetime.datetime.now()
print(a)
a = datetime.datetime.now()
print(a.year)
a = datetime.datetime(2050,11,11)
print(a)
a = datetime.datetime(2020,6,19)
print(a.strftime('%d'), a.strftime('%B'))

2020-05-23 00:57:02.916682
2020
2050-11-11 00:00:00
19 June


In [221]:
#to print even numbers 
for i in range(10):
    if i%2 == 0:
        print(i)

0
2
4
6
8


In [222]:
#to print odd numbers 
for i in range(10):
    if i%2 == 0:
        print(i+1)

1
3
5
7
9


9.	Write a program that prints the  umber from 1 to 25. but for multiple  of three print ’Fizz’ instead of the number and for the multiple of number 5 print ‘Buzz’, for numbers multiple of 3&5 print ‘FizzBuzz’.

In [223]:
for i in range(1,25):
    if i%3 == 0 and i%5 == 0:
        print('FizzBuzz')
        continue
    elif i%3 == 0:
        print('Fizz')
        continue
    if i%5 == 0:
        print('Buzz')
        continue
    print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz


In [224]:
#OR
for i in range(1,25):
    if i%3 != 0 and i%5 != 0:
        print(i)
    if i%3 == 0:
        print('Fizz')
    if i%5 == 0:
        print('Buzz')
    if i%3 == 0 and i%5 == 0:
        print('FizzBuzz')

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
Fizz
Buzz
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz


In [225]:
# Get service provider name of any mobile number usning python

import phonenumbers
from phonenumbers import carrier
mobileno = input("enter mobile number with country code: ")
service_provider = phonenumbers.parse(mobileno)
print(carrier.name_for_number(service_provider, 'en'))

enter mobile number with country code: +919480241564
BSNL MOBILE


In [181]:
# TO print sum of number user entered unti he enter zero
num = 1
sum = 0
print('please enter a number, enter zero(0) to exit')
while num != 0:
    num = float(input('number ?'))
    sum = sum + num;
    print('sum is: ', sum)
else:
    print('finished sum')

please enter a number, enter zero(0) to exit
number ?1
sum is:  1.0
number ?2
sum is:  3.0
number ?3
sum is:  6.0
number ?0
sum is:  6.0
finished sum


## FOR LOOP

In [200]:
a = [0,1,2,3,4,5] #-List
b = (0,1,2,3,4,5) #-Tuple
c = (0,1,2,3,4,5) #-Set
d = '012345'      #-String
e = {'name':'akshay', 'age':25}   #-Dictionary
print(a)
print(0 in a)
print(100 in a)
print('1' in d)

[0, 1, 2, 3, 4, 5]
True
False
True


In [202]:
for i in a:
    print(i)

0
1
2
3
4
5


In [203]:
for i in b:
    print(i)

0
1
2
3
4
5


In [220]:
for i in e:
    print(i)
print('\nkeys are:-')
for i in e.keys():
    print(i)
print('\nvalues are:-')
for i in e.values():
    print(i) 
print('\nkey & values are:-')
for key, value in e.items():
    print(key, '', value)     

name
age

keys are:-
name
age

values are:-
akshay
25

key & values are:-
name  akshay
age  25


In [222]:
#print 0 to 5 values
for x in range(6):
    print(x)

0
1
2
3
4
5


In [224]:
#print 3 to index 6 values
for x in range(3, 6):
    print(x)

3
4
5


In [227]:
#print 0 to 20 interval of 5
for x in range(0,20,5):
    print(x)

0
5
10
15


In [243]:
# Bresk statement --> it will skip loop when specified value is true
a = [0,1,2,3,4,5]
for x in a:
    if x == 3:
        break
    print(x)

0
1
2


In [245]:
# Continue statement --> It will skip specified value
a = [0,1,2,3,4,5]
for x in a:
    if x == 3:
        continue
    print(x)
print('===================')
z = 0
while z < 5:
    z += 1
    if z == 3:
        continue
    print(z)   

0
1
2
4
5
1
2
4
5


### Regular Expression in Python

In [237]:
import re
print(re.match('a' , 'akshaykumar'))
print(re.match('b' , 'akshaykumar'))

<re.Match object; span=(0, 1), match='a'>
None


In [243]:
m = re.search('\bopen\b', 'please open the door')
print(m)

None


## LISTS

In [52]:
empty_list = []
type(empty_list)

list

In [53]:
houses = ['Stark', 'Targaryen', 'Lannister', 'Baratheon']
print (houses) 

['Stark', 'Targaryen', 'Lannister', 'Baratheon']


In [126]:
# We can have multiple datatype element sin list
list = [4,6, 'akshay', 'abhi', 5.5, 4.6789]
list

[4, 6, 'akshay', 'abhi', 5.5, 4.6789]

In [54]:
season1 = 1
season2 = 2
videos = 'i love wtaching series videos'
info = [season1,season2,videos]
print(info)

[1, 2, 'i love wtaching series videos']


In [251]:
List = ['Red', 'Green', 'Black', 'Blue']
for i in range(len(List)):
    print(i, List[i])

0 Red
1 Green
2 Black
3 Blue


In [256]:
#Enumerating a List
#With the help of Python enumerate function, we can iterate over the index and value in a Python list by using a basic for loop. Let us see how:
list = ['Red', 'Green', 'Black', 'Blue']
for i, j in enumerate(list):
    print(i, j)

0 Red
1 Green
2 Black
3 Blue


In [257]:
#With the help of enumerate, we can create a Python Dictionary out of a list very easily.
list = ['Red', 'Green', 'Black', 'Blue']
Dict= dict(enumerate(List))
print(Dict)

{0: 'Red', 1: 'Green', 2: 'Black', 3: 'Blue'}


In [258]:
#Enumerating a List of Tuples
#Example:

List1 = [(10,'Red'), (5,'Green'), (8,'Black'),(2,'Blue')]
for idx, (count, color) in enumerate(List1):
    print(idx, count, color)

0 10 Red
1 5 Green
2 8 Black
3 2 Blue


In [265]:
#Enumeratinf a string
string = 'Akshay'
for i, j in enumerate(string):
    print(i, j)

print('')    
#Enumerating from a Specific Index    
string = 'Akshay'
for i, j in enumerate(string, 1):
    print(i, j)

0 A
1 k
2 s
3 h
4 a
5 y

1 A
2 k
3 s
4 h
5 a
6 y


In [55]:
list('aeiou')

['a', 'e', 'i', 'o', 'u']

In [56]:
print(['a', 'e', 'i', 'o', 'u'] + [11, 22, 33])

['a', 'e', 'i', 'o', 'u', 11, 22, 33]


In [58]:
Names = ['Akshay', 'Abhi']
print(Names*3)

['Akshay', 'Abhi', 'Akshay', 'Abhi', 'Akshay', 'Abhi']


In [67]:
#Indexing and Slicing 
basket = ["apples", "grapes", "oranges", "mangoes", "bananas"]
print(basket[0])
print(basket[4])
print(basket[-1])
print(basket[0:1])
print(basket[1:1])
print(basket[1:4])

apples
bananas
bananas
['apples']
[]
['grapes', 'oranges', 'mangoes']


#Nesting
Lists can be nested i.e., you can have list within list. Items of nested lists (list of lists) can be accessed by multiple indexing.

In [69]:
characters = [ ['Cercie', 'Jammie', 'Tyrion'], ['Arya', 'Rob', 'Bran'] ] 
print(characters [0][2] )
print(characters [1][0])

Tyrion
Arya


##Lists are mutable
Unlike strings, lists are a mutable, i.e. item of a list can be changed.

In [72]:
nums = [0, 11, 22, 33, 44, 55] 
nums[2] =99
print(nums)
nums [3:5] = [300, 400]
print(nums)
nums [1:3] = []
print(nums)

[0, 11, 99, 33, 44, 55]
[0, 11, 99, 300, 400, 55]
[0, 300, 400, 55]


In [ ]:
#del statement
Just as del statement deletes a variable, it can delete item(s) from a list.

In [73]:
even_nums = [22, 44, 55, 66, 88]
del  even_nums[2] 
print(even_nums)
del even_nums[1:3]
print(even_nums)
del even_nums
print(even_nums)

[22, 44, 66, 88]
[22, 88]


NameError: name 'even_nums' is not defined

#in and not operators 
These check if an item belongs to a given list and return either True or False (boolean type).

In [79]:
bag_of_words = ["include", "reverse", "response", "lazy"] 
print('include' in bag_of_words )
print('path' in bag_of_words )
bag_of_words = ["include", "reverse", "response", "lazy"]
print('render' not in bag_of_words)

True
False
True


In [81]:
#len() and sum()
prime_nums = [2, 3, 5, 7, 11]
print(len(prime_nums))
x = [951, 753]
print(sum(x)) 

5
1704


#Strings and Lists
str.split() 
Strings can be directly casted into a list using list() constructor. A better option is to use str.split() method which is more flexible than list() constructor.

In [85]:
martell = 'Unbowed Unbent Unbroken' 
print(list (martell))
print(martell.split())

['U', 'n', 'b', 'o', 'w', 'e', 'd', ' ', 'U', 'n', 'b', 'e', 'n', 't', ' ', 'U', 'n', 'b', 'r', 'o', 'k', 'e', 'n']
['Unbowed', 'Unbent', 'Unbroken']


In [87]:
local_host = '127.0.0.1' 
print(local_host.split())
print( local_host.split('.'))

['127.0.0.1']
['127', '0', '0', '1']


In [93]:
emails = 'abc@gmail.com xyz@yahoo.com' 
print(emails.split())
print(emails.split('@'))
message = 'Humanxafterxall'
print(message.split())
print(message.split('x'))

['abc@gmail.com', 'xyz@yahoo.com']
['abc', 'gmail.com xyz', 'yahoo.com']
['Humanxafterxall']
['Human', 'after', 'all']


In [ ]:
#str.join() 
It returns a string that is created by joining a list of strings on a particular character.

In [100]:
x = ['Make', 'Me', 'Crazy'] 
print(''.join (x) )
print(' '.join (x))
print('#'.join (x) )
print( '_'.join (x))

MakeMeCrazy
Make Me Crazy
Make#Me#Crazy
Make_Me_Crazy


In [102]:
s = 'too often the only escape is sleep'
m = s.split()
print(m)
x = '_'.join (m)
print(x)

['too', 'often', 'the', 'only', 'escape', 'is', 'sleep']
too_often_the_only_escape_is_sleep


## List methods

In [103]:
#list.append (x) :- It adds an item at the end of the list.
branches = ['CSE', 'ECE'] 
branches.append('IT') 
print(branches)

['CSE', 'ECE', 'IT']


#list.copy ()
It returns a shallow (new) copy of the list. It is equivalent to x[:]

#list.count (x) 
It returns the number of times an item appears in the list

In [1]:
score_card = [14, 35, 4, 68, 14, 36, 88, 35] 
score_card.count (14) 

2

#list.extend (iterable) 
It appends all the items from an iterable to the list one by one. Iterable is an object that is capable of returning its members one at a time, all sequence types like lists, str are iterable.

In [3]:
houses = ['Stark'] 
houses.extend('Targaryen') 
print(houses)
del houses[1:]
print(houses)
houses.append('Targaryen') 
print(houses)
x = ['Lannister', 'Baratheon', 'Mormont']
houses.append (x)
print(houses)
del houses[2] 
print(houses)
houses.extend (x)
print(houses)

['Stark', 'T', 'a', 'r', 'g', 'a', 'r', 'y', 'e', 'n']
['Stark']
['Stark', 'Targaryen']
['Stark', 'Targaryen', ['Lannister', 'Baratheon', 'Mormont']]
['Stark', 'Targaryen']
['Stark', 'Targaryen', 'Lannister', 'Baratheon', 'Mormont']


#list.index (item)
It returns the index of first instance of an item in the list.

In [4]:
house_arryn = ['Jon', 'Lysa', 'Robert'] 
house_arryn.index ('Lysa') 

1

#list.insert (i, x) 
It adds an item at a particular index to a list.

In [5]:
house_stark = ['Eddard', 'Catelyn', 'Robb', 'Arya', 'Bran'] 
house_stark.insert(3, 'Sansa')
print(house_stark)

['Eddard', 'Catelyn', 'Robb', 'Sansa', 'Arya', 'Bran']


LIST.remove() #removes the girst element from the list

LIST.remove('name') #Removes the element which having name 'name'

LIST.POP()   #Removes the last element from the list

LIST.clear()  #Removes all values from list

LIST.count(10)  #Returns the number of '10' value counts from list

In [122]:
#Creating copy of list
x = [1,2,3]
y = x.copy()
y

[1, 2, 3]

#list.pop (i) 
It removes item from a specific index. If no argument is passed, removes the last item from list and the removed item is returned.

In [8]:
house_tyrell = ['Mace', 'Olenna', 'Margaery', 'Loras'] 
house_tyrell.pop () 
print(house_tyrell)
removed_name = house_tyrell.pop (1) 
print(removed_name)
print(house_tyrell)

['Mace', 'Olenna', 'Margaery']
Olenna
['Mace', 'Margaery']


#list.remove (x) 
It removes the item passed as argument and returns nothing. In Python, None object refers to nothing.

In [9]:
house_greyjoy = ['Balon', 'Theon', 'Yara'] 
removed_name = house_greyjoy.remove ('Theon') 
print(removed_name)
print(type(removed_name))
print(house_greyjoy)

None
<class 'NoneType'>
['Balon', 'Yara']


#list.reverse () 
It reverses the order of items in a list. This method is inplace i.e., its effect is reflected to the original list as soon as it is called. None object is returned by this method.

In [11]:
house_baratheon = ['Robert', 'Stannis', 'Renly'] 
print(house_baratheon)
house_baratheon.reverse() 
print(house_baratheon)

['Robert', 'Stannis', 'Renly']
['Renly', 'Stannis', 'Robert']


#list.sort () 
It sorts a numeric list in ascending order and a string list in alphabetical order. This method is also inplace and returns nothing.

In [15]:
countries = ['Spain', 'Canada', 'France', 'Turkey', 'China'] 
countries.sort()
print(countries)
nums = [33, 11, 22, 99] 
nums.sort () 
print(nums)

['Canada', 'China', 'France', 'Spain', 'Turkey']
[11, 22, 33, 99]


## ARRAYS

 An array is a data structure that can contain or hold a fixed number of elements that are of the same Python data type.

 Difference between Array and List in Python

The basic difference between arrays and lists in Python is that lists are flexible and can hold completely arbitrary data of any data type while arrays can only hold data of the same data type.

Arrays are considered useful in terms of memory efficiency, but they are usually slower than lists.

## Tuples: 

#Immutable lists
#tuple, which is very similar to list data type. Unlike lists, tuples are immutable i.e., you can’t modify the value of an item, once you’ve created a tuple of items

In [20]:
empty_tuple = ()
print(empty_tuple)
x = 'akshay'
print(type(x))
x = 'akshay',   #Given comma after strong
print(type(x))

()
<class 'str'>
<class 'tuple'>


In [123]:
#we can have multiple datatype values in tuple
y =(5, 'akshay', 5.5)
y

(5, 'akshay', 5.5)

In [128]:
# we can create tuple concating other tuples
x = (1,2,3,4,5)
y =(5, 'akshay', 5.5)
z = x + y
z

(1, 2, 3, 4, 5, 5, 'akshay', 5.5)

In [129]:
a = ('hi',)*5
a

('hi', 'hi', 'hi', 'hi', 'hi')

In [131]:
#to delete tuple 
del a
a

NameError: name 'a' is not defined

In [21]:
#Tuple are immutable -we cananot alter tuple once created
my_tuple = (11, 22, 33, 44, 55, 66)
my_tuple[3] = 99

TypeError: 'tuple' object does not support item assignment

In [22]:
list = [1,2,3]
tuple = tuple(list)
print(tuple)

(1, 2, 3)


In [25]:
# Sometimes items are not enclosed in (), which is referred to as tuple packing and reverse process as tuple unpacking.
# tuple packing 
x = 'one', '2', 'three'
print(x)
print(type(x))

# tuple unpacking
a, b, c = x
print (a, b, c) 

('one', '2', 'three')
<class 'tuple'>
one 2 three


1. Concatenation and Replication

In [27]:
('a', 'e', 'i', 'o', 'u') + (11, 22, 33) 

('a', 'e', 'i', 'o', 'u', 11, 22, 33)

In [28]:
a = ('Harry', 'Potter') 
print(a*3)

('Harry', 'Potter', 'Harry', 'Potter', 'Harry', 'Potter')


2. Indexing and Slicing 
Tuple items can be accessed by indexing or unpacking.

In [32]:
basket = ("apples", "grapes", "oranges", "mangoes", "bananas")
print(basket [0])
print(basket [-1])
print(basket [2:5])
print(basket [4])

apples
bananas
('oranges', 'mangoes', 'bananas')
bananas


2.1 Nesting

In [34]:
characters = ( ('Cercie', 'Jammie', 'Tyrion'), ('Arya', 'Rob', 'Bran') ) 
print(characters [0][2]) 
print( characters [1][0])

Tyrion
Arya


#Tuple methods
Tuples have only two methods tuple.count() and tuple.index(). tuple.count(): Returns number of occurrences of an item. 
tuple.index(): Returns index of first instance of an item

In [38]:
house_targaryen = ('Daenerys', 'Viserys', 'Aerys') 
print(house_targaryen.index('Aerys'))
print(house_targaryen.count('Daenerys'))

2
1


## Dictionary

- A Dictionary is a set of key-value pairs, with the requirement that the keys are unique. These are also called as associative arrays or Hash tables in other programming languages.
- dictionary are list of pairs
- A dictionary is a comma-separated list of key:value pairs enclosed within curly braces {}. A value can be accessed by calling the key of that particular value like my_dict[key], if key is not present, KeyError is thrown.
-  Dictionaries are mutable. All mappings are mutable objects, as dictionaries are the only built-in mapping type in Python, they can be modified.
-  Dictionaries are unordered objects. Unlike sequence types, dictionaries don’t preserve order of its items. A dictionary is an associative array, where keys are mapped to their values.


In [42]:
empty_dict = {}
print(empty_dict)
ginger = {'name': 'Yigrette', 'allegiance': 'Free Folk', 'season': 2}
print(ginger)
print(ginger["name"])
print(ginger[name]) #name is string not variable

{}
{'name': 'Yigrette', 'allegiance': 'Free Folk', 'season': 2}
Yigrette


NameError: name 'name' is not defined

In [45]:
#Dictionaries are mutable
tyrion = {'origin': 'Casterly Rock', 'title': 'Master of Coin'} 
tyrion ['age'] = 38
print(tyrion)
tyrion ['title'] = 'Hand of the Queen'
print(tyrion)
del tyrion ['origin']
print(tyrion)

{'origin': 'Casterly Rock', 'title': 'Master of Coin', 'age': 38}
{'origin': 'Casterly Rock', 'title': 'Hand of the Queen', 'age': 38}
{'title': 'Hand of the Queen', 'age': 38}


In [46]:
factors = {6: [1,2,3], 8: [1,2,4]} 
print(factors [6] )

[1, 2, 3]


In [47]:
lcm = {[1,2,3]: 6, [1,2,4]: 8}

TypeError: unhashable type: 'list'

In [50]:
lcm = {(1,2,3): 6, (1,2,4): 8}
lcm[(1,2,3)]        

6

#Dictionary methods

1. dict.clear () 
Empty your dictionary with this method.

In [53]:
ollena = {'house': 'Tyrell', 'title': 'Queen of thorns'} 
print(ollena)
ollena.clear()
print(ollena)

{'house': 'Tyrell', 'title': 'Queen of thorns'}
{}


#dict.copy () 
It returns a shallow (new) copy of the dictionary.

#dict.get (key) 
If key is in the dictionary, it returns its corresponding value. If key is not present, instead of raising KeyError, it returns nothing.

In [55]:
my_device = {'RAM': '3 GB', 'model name': 'MC13x'} 
print(my_device.get('model name')) 
print(my_device.get('baseband version'))

MC13x
None


#dict.pop (key) 
It remove a specified key and returns the corresponding value.

In [58]:
nums = {'one': 1, 'two': 2, 'three': 3}
print(nums.pop ('one')) 
print(nums)
nums.pop ('four')

1
{'two': 2, 'three': 3}


KeyError: 'four'

## SETS

-  A set is an unordered collection of unique elements. 
- sets dont preserve order
- sets doesnot have duplicate value
- sets doesnot have indexing
- empty pair of curly braces {} creates a dictionary not a set. If you want to instantiate an empty set object use set() constructor.
- Sets are mutable

In [133]:
a = {11, 22, 33, 44, 22, 22, 11}
print(a) 
# sets dont preserve order
# it removes duplicate values and keep only unique values

{33, 11, 44, 22}


In [149]:
# we can have any type of elements in set
b = {1,2, 'akshay', 5.5, 2, 'abhi'}
b

{1, 2, 5.5, 'abhi', 'akshay'}

In [144]:
a.add(55) #it will add 55 to set
a.add(11)  #as 11 is already existed in set it will not add 11 
print(a)
a.update([15,16,18])
print(a)
a.remove(18) #it reoves element 18 from set
print(a)
a.discard(17)  #it works like remove and reoves element 17 from set
print(a)
#Difference betweetn remove and discard is whenever element which we try to remove is not present in set it will throw error, but discard will nt thow error
a.pop()  # It will remove any random element from set
print(a)
a.clear()   #removes all elements from set
print(a)
del a
print(a)  #Delete set

{11, 55}
{11, 15, 16, 18, 55}
{11, 15, 16, 55}
{11, 15, 16, 55}
{11, 16, 55}
set()


NameError: name 'a' is not defined

In [145]:
# we can also create set like
name = set(('akshay', 'abhi', 'srey'))
name

{'abhi', 'akshay', 'srey'}

In [147]:
# we can create set from list
z = set([3,4,6,7])
z

{3, 4, 6, 7}

In [158]:
#index is not possibke in sets, because sets are unordered collection of eements
z[0]

TypeError: 'set' object is not subscriptable

In [156]:
# we can perform mathematical operations on set
set1 = {1,2,3,4,5,6}
set2 = {5,6,7,8,9,10}
#Union
union = set1 | set2  #or set1.union(set2)
print(union)
#intersection
intersect = set1 & set2 #or set1.intersection(set2)
print(intersect)
#difference
print(set1 - set2)   #or set1.difference(set2)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{5, 6}
{1, 2, 3, 4}


In [63]:
age_set = {14, 16, 12, 16, 13, 14, 15, 13} 
print(age_set)
eye_color_list = ['black', 'brown', 'black', 'blue', 'green', 'brown'] 
distinct_eye_colors = set(eye_color_list)
print(distinct_eye_colors)
set('Floccinaucinihilipilification')
print(set(('Red', 'Woman')))

{12, 13, 14, 15, 16}
{'green', 'black', 'brown', 'blue'}
{'Red', 'Woman'}


## FUNCTIONS
- function is a group of statements within a program that performs a specific task
- Functions are of 2 types
    - Built in functions  (ex: print(), min(), input()) - function do a single task at a time
    - user defined functions
    
- using function we can test & debug code easily

In [254]:
def sum(arg1, arg2):
    print(arg1 + arg2)

sum(2,4)
sum(2.5, 1.5)
sum('hello ', 'world')
sum(2, 'akahay')

6
4.0
hello world


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [277]:
#when summing twi different data types number and char we get error to handle that  
def sum(arg1, arg2):
    if type(arg1) != type(arg2):
        print('please provide args of same type')
        return
    print(arg1 + arg2)
        

sum(2,4)
sum(2.566,4.566)
sum('hello ', 'world')
sum(2, 'akahay')

6
7.132
hello world
please provide args of same type


In [282]:
def sum(arg1, arg2):
    if type(arg1) != type(arg2):
        print('please provide args of same type')
        return
    return (arg1 + arg2)
#when we are using return statement for output then we need to call variable tp store function output or print function output

a = sum(2, 4)
print(a)
print(2.566,4.566)
print(sum('hello ', 'world'))
sum(2, 'akahay')

6
2.566 4.566
hello world
please provide args of same type


In [286]:
# * -> Asteric in Function
# using Asteric symbol we can pass any number of values for that argument
def student(name = 'unknown name', age = 0, *marks):
    print('name is =', name)
    print('age is = ', age)
    print('marks are =', marks)   #stored marks as tuple
    for i in marks:
        print(i)

student('akshay', 25, 90,95,96,98)        

name is = akshay
age is =  25
marks are = (90, 95, 96, 98)
90
95
96
98


In [294]:
# ** -> Double Asteric in Function
# using Asteric symbol we can pass any number of values for that argument and also assign key vale pair
def student(name = 'unknown name', age = 0, **marks):
    print('name is =', name)
    print('age is = ', age)
    print('marks are =', marks)   #stored marks as tuple
    for i in marks:
        print(i)
    print('\nkey value pair are: ')    
    for key, value in marks.items():
        print(key, ' ', value)

student('akshay', 25, maths=90, english=95, science=96, history=98)        

name is = akshay
age is =  25
marks are = {'maths': 90, 'english': 95, 'science': 96, 'history': 98}
maths
english
science
history

key value pair are: 
maths   90
english   95
science   96
history   98


In [246]:
def greet_me(name):
    print('Welcome %s' %name)
    
name = 'akshay'
greet_me(name)          

Welcome akshay


In [76]:
def greet_me(name):
    print(f'Welcome {name}')

name = 'hcl technologies'
greet_me(name)          

Welcome hcl technologies


In [79]:
def even_odd(num):
    if(num % 2 == 0):
        print(f'{num} is even')
    else:
        print(f'{num} is odd')

even_odd(10)        
even_odd(11)

10 is even
11 is odd


1. Keyword Argument
An argument preceded by an identifier in a function call, like some_func(age=99), or passed as a value in a dictionary preceded by **

In [81]:
print(round(number=123.345, ndigits=2))
print(round (**{'number': 1.2154785, 'ndigits': 3}))

123.34
1.215


2. Positional Argument
Positional arguments can be passed directly without any identifier, or as elements of an iterable preceded by *.

In [82]:
print(round(2.718281828, 4))
print(round(*(2.718281828, 4)))

2.7183
2.7183


Return statement
The return statement returns a value (or an expression) from a function. Function without a return statement returns None. Remember, None type represents the absence of an object.

In [83]:
def cube_num(num):
    return num**(1/3)

print(cube_num(27))

3.0


In [85]:
def goblin ():
    print ("I wont return anything.")
x = goblin () 
print (f"goblin() returns {x}")

I wont return anything.
goblin() returns None


In [87]:
def display (name, age, height):
    print (f"{name}, who has {height} cm height, is {age} years old.")
    
display('Tormund', 29, '185') 
display(160, 'Ryan', 15) 
display(age=19, height=175, name='Mark.')

Tormund, who has 185 cm height, is 29 years old.
160, who has 15 cm height, is Ryan years old.
Mark., who has 175 cm height, is 19 years old.


In [92]:
def swap(x,y):
    temp = x
    x = y
    y = temp
    return(x,y)

a = 11
b = 12
print(f'values befoe swap \n a: {a}, b: {b} \n')
a,b = swap(a,b)
print(f'values befoe swap \n a: {a}, b: {b} \n')

values befoe swap 
 a: 11, b: 12 

values befoe swap 
 a: 12, b: 11 



In [93]:
#You can also swap two values without using a temporary variable.
def swap (x, y):
    x = x+y
    y = x-y
    x = x-y
    return (x, y)
a = 11
b = 22
print(f'Values before swapping \na: {a}, b:{b}\n') 
a, b = swap (a, b)
print (f'Values afrer swapping \na: {a}, b:{b}')

Values before swapping 
a: 11, b:22

Values afrer swapping 
a: 22, b:11


In [95]:
#Cumilative Sum
def cum_sum(num):
    if(num == 0):
        return 0
    else:
        return (num*(num+1)/2)

print(cum_sum(10))    

55.0


1. map() function
It maps a function to an iterable i.e., it allows you to apply a function to an iterable by iterating through every item. map() function returns a generator like range().
SYNTAX:-
map (function, iterable)

2. filter() function
If a function filters the input based on some condition and returns either True or False, use filter function. The filter function works same as map, the only difference is, filter only returns those values of an iterable for which function is True.  Like map(), it is also a generator function.
Syntax:-
filter (function, iterable)

lambda expression
A lambda function has, no def, no return keyword; just arguments and an expression. 
Syntax:-
lambda arg1, arg2, ... : expression
Lambda expressions are more useful when used with Python’s built-in map() and filter() functions.

In [191]:
cube_root  = lambda x: x**(1/3)
print(cube_root(27))

3.0


#Default argument values
While defining a function you can set its arguments to a default value; if the function is called, without passing a value for that particular argument, default value for argument is set automatically. If value is passed then default value is overwritten with the value passed during the call.

In [206]:
def choice(name, language='Python'):
    print(f'{name} likes {language}')

choice('akshay')
choice('girish', 'java')

akshay likes Python
girish likes java


In [210]:
def word_to_letter (word, alphabets=[]):
    for i in word:
        alphabets.append(i)
    print (alphabets)
word_to_letter ('Palestine') 
word_to_letter ('Kashmir')

['P', 'a', 'l', 'e', 's', 't', 'i', 'n', 'e']
['P', 'a', 'l', 'e', 's', 't', 'i', 'n', 'e', 'K', 'a', 's', 'h', 'm', 'i', 'r']


*args and **kwargs
A function can have multiple arguments, or no arguments at all. If you’re not sure about the number of parameters while defining a function, you can simply pass *args to have an arbitrary number of arguments in the form of a tuple.
*args can be replaced with any other name of your choice like *chocolate, but it’s a Pythonic convention to use *args.

In [212]:
def squared_third_item (*args):
    if (len (args) > 2): 
        return args[2]**2
    else:
        print ('Insufficient length.')

a = squared_third_item(7, 13, 2, 8)
b = squared_third_item(11, 22, 33, 44, 55)
print(a, b, sep='\t')
c = squared_third_item () 
print (c)

4	1089
Insufficient length.
None


In [213]:
def is_even (*args):
    even_list = [num for num in args if num%2==0] 
    return even_list

print (is_even(11,22,33,44,55,66))

[22, 44, 66]


**kwargs (Keyword arguments) are frequently used to handle the cases where you have arbitrary number of arguments. Instead of tuples, it receives a dictionary containing all keyword arguments.

In [214]:
def student_info (**kwargs): 
    print (f"Name: {kwargs['name']} \tEnroll: {kwargs['enroll']}")

student_info (name='Jose', age=19, enroll=213) 
student_info (name='Mark', enroll=240, hair_color='black')

Name: Jose 	Enroll: 213
Name: Mark 	Enroll: 240


In [215]:
def student_info (**kwargs):
    print (f"Name: {kwargs['name']} \tEnroll: {kwargs['enroll']}")

student_info (**{'name': 'Jose', 'age': 19, 'enroll': 213}) 
student_info (**{'name': 'Mark', 'enroll': 240, 'hair_color': 'black'})

Name: Jose 	Enroll: 213
Name: Mark 	Enroll: 240


In [217]:
def student_info (**kwargs): 
    print(f"Name: {kwargs['name']} \tEnroll: {kwargs['enroll']}")

student_info ('Joshua', age=23, enroll=619)

TypeError: student_info() takes 0 positional arguments but 1 was given

Combining *args and **kwargs
In a function call, positional arguments must appear first which are then followed by keyword arguments. 

In [ ]:
def total_sales(*args, **kwargs): 
    total = sum(args) 
    print(f"{kwargs['day']} sales:{total}")

total_sales(73,15, day='Wednesday') 
total_sales(14,65,33, day='Friday')

## if __name__ == "__main__":
Read regarding this

### CLASS

- class refers to blueprint in which we can have data and methods

- using class we can create objects

- Object: = object is an istance of class 
    - Object is a software unit which combines data and methods
    - in below ex objects are cab, cabdriver, passanger - these objects can exchange data between them

- Methods: = Functions used inside the class is claled methods

- Attributes: = variables inside class which stores some informatio  or data 

- Using classes we can create object of class

In [297]:
'''
class cab{
    cabservice, make, locationm numberplate  #data
    book(), arrival(), start()               #Methods
    }

Class cabdriver{
    name, emplid   #data
    opendoor(), drive()   #methods
    }
    
class passanger {
    name, address    #data
    openapp(), bookcab(), walk()  #Methods
}    
}
    '''

'\nclass cab{\n    cabservice, make, locationm numberplate  #data\n    book(), arrival(), start()               #Methods\n    }\n\nClass cabdriver{\n    name, emplid   #data\n    opendoor(), drive()   #methods\n    }\n    \nclass passanger {\n    name, address    #data\n    openapp(), bookcab(), walk()  #Methods\n}    \n}\n    '

In [302]:
class car:
    pass

# this pass keyword Creating a empty class
# also can use pass keyword used to create empt methos 

# Create object/instance of class
ford = car()   # ford is object/instance of class car
honda = car()
audi = car()

#associate some data with objects
ford.speed = 200   # here speed is the attribute/variable
honda.speed = 220
audi.speed = 250

ford.color = 'red'     # here color is the attribute/variable
honda.color = 'blue'
audi.color = 'black'

print(ford.speed)
print(ford.color)

ford.speed = 300
ford.color = 'white'
print(ford.speed)
print(ford.color)

200
red
300
white


In [306]:
class Rectangle:
    pass

rect1 = Rectangle()
rect2 = Rectangle()

rect1.width = 20
rect1.height = 30

rect2.width = 40
rect2.height = 10

#Calculate area of rectangle
print(rect1.height * rect1.width)
print(rect2.height * rect2.width)

600
400


In [308]:
class car:
    def __init__(self):              #we use 'self' convenstion to indicate its current object, its not necessary thatwe use 'self' we can use any charecter indcation
        print('the __init__ is called')

# init method serves as constructor for class
# init methos used to initialize some attributes or functions
# init is the first methos is cllaed when we create instance of class

ford = car()   # ford is object/instance of class car
honda = car()
audi = car()

#associate some data with objects
ford.speed = 200   # here speed is the attribute/variable
honda.speed = 220
audi.speed = 250

ford.color = 'red'     # here color is the attribute/variable
honda.color = 'blue'
audi.color = 'black'

print(ford.speed)
print(ford.color)

ford.speed = 300
ford.color = 'white'
print(ford.speed)
print(ford.color)

the __init__ is called
the __init__ is called
the __init__ is called
200
red
300
white


#lone 'the __init__ is called' called 3 times becuse we created 3 instance from same class
#every time we create instance this lone is printed, rest print statements from instnace of classes will be printed
#_Init_ is first method to be called whenever instance is created 
#Python don't have distructor as python take care of itself

In [310]:
class car:
    def __init__(self, speed, color):
        print(speed)
        print(color)
        print('the __init__ is called')

ford = car(200, 'red')   # ford is object/instance of class car
honda = car(250, 'blue')
audi = car(220, 'white')

200
red
the __init__ is called
250
blue
the __init__ is called
220
white
the __init__ is called


In [313]:
class car:
    def __init__(self, speed, color):
        print(speed)
        print(color)
        self.speed = speed
        self.color = color
        print('the __init__ is called')

ford = car(200, 'red')   # ford is object/instance of class car
honda = car(250, 'blue')
audi = car(220, 'white')
print(' ')
print(ford.speed)
print(ford.color)

200
red
the __init__ is called
250
blue
the __init__ is called
220
white
the __init__ is called
 
200
red


In [318]:
class Rectangle:
    def __init__(self, height, width):
        self.height = height
        self.width = width

rect1 = Rectangle(20, 30)
rect2 = Rectangle(50, 20)

print(rect1.height * rect1.width)
print(rect2.height * rect2.width)

600
1000


In [326]:
# we should always pass 'self' parameter to __init__, else it will trow error
# only one __init__ methos have to use inside class, if more used then the last __init__ will be taken
class Hello:
    def __init__(self): pass
    def __init__(self, name): 
        self.name = name

hello = Hello('akshay')  
print(hello.name)

akshay


In [329]:
class Hello:
    def __init__(self, name='akshay'): 
        self.name = name

name1 = Hello()  
print(name1.name)

name2 = Hello('abhi')  
print(name2.name)

akshay
abhi


In [340]:
class Hello:
    def __init__(self, *args): # here *args can take any number of parameters
        self.args = args

names = Hello('akshay','abhi', 'mahesh', 'suresh')  
print(names.args)

('akshay', 'abhi', 'mahesh', 'suresh')


In [343]:
class Hello:
    def __init__(self, **kwargs): # here *args can take any number of parameters
        self.kwargs = kwargs

names = Hello(name = 'akshay', age = 28, sex = 'male', sal = 2000)  
print(names.kwargs)

{'name': 'akshay', 'age': 28, 'sex': 'male', 'sal': 2000}


### encapsulation

In [372]:
# to make data private 
# python uses  double underscore '__' convetion to make data private
# this private is used for data encapsulation(to restrict data from users)
# encplsulation is restricting data access
class Hello:
    def __init__(self, name):
        self.a = 10
        self._b = 20
        self.__c = 30

hello = Hello('name')
print(hello.a)
print(hello._b)
print(hello.__c)    #when use __c we get error as AttributeError: 'Hello' object has no attribute '__c' becuase it acts like private

10
20


AttributeError: 'Hello' object has no attribute '__c'

In [364]:
# Enclapsulation
# we can restrict users to change variable values 
class Rectangle:
    def __init__(self, height, width):
        self.__height = height
        self.__width = width
    
    def set_height(self, height):
        self.__height = height
    def get_height(self, height):
        return self.__height    
    
    def set_width(self, width):
        self.__width = width
    def get_height(self, width):
        return self.__width       
    
    def area(self):
        return self.__height * self.__width       
        
rect = Rectangle(10,20)   
print(rect.area())
#print(rect.height)   # We cannot access 'height' as its encapsulated
#print(rect.width)    # We cannot access 'width' as its encapsulated

200


In [362]:
# Enclapsulation
class Rectangle:
    def __init__(self, height, width):
        self.__height = height
        self.__width = width
    
    def area(self):
        return self.__height * self.__width
rect = Rectangle(10,20)   
print(rect.area())        

200


In [379]:
# Defining private methos
class Hello:
    def __init__(self, name):
        self.a = 10
        self._b = 20
        self.__c = 30
        
    #defining private class methos
    def __private_method(self):   # We can define methos as private by using __ before to it, we cannot access this method outside this class
        print('private')    
    
    #using private class variabe insdie a class methos
    #using private class methos inside another class methos
    def public_method(self):
        print(self.a)
        print(self.__c)    #we can access '__c' variable inside class methods
        print('public')
        self.__private_method()
    
        
hello = Hello('name')
print(hello.a)
print(hello._b)
hello.public_method()
#hello.__private_method()   #AttributeError: 'Hello' object has no attribute '__private_method'

10
20
10
30
public
private


### Inheritance
- creating new class which retain charecteristics of the base class is called inheritance
- involves superclass & subclass
- the subclass inherits the members of the superclass, on top of which it can add its own members
- idea behind inheritance is the new class can borrow the behaviors & methos from another class

In [391]:
class Polygon:
    __width = None  # we are using '__' to make vaibales as private
    __height = None
    
    def set_vlaues(self, width, height):
        self.__width = width
        self.__height = height

class Rectangle(Polygon):
    def area(self):
        return self.__height * self.__width
    
class Triangle(Polygon):
    def area(self):
        return self.__height * self.__width /2       
    
# Polygon = superclass 
# Rectangle & Triangle = subclasses
# we ae inheriting properties from Polygon to subclasses

rect = Rectangle()   # Created rectangle instance
tri = Triangle()    # cteated triangle instance

rect.set_vlaues(10, 20)
tri.set_vlaues(10,20)

print(rect.area())
print(tri.area())

AttributeError: 'Rectangle' object has no attribute '_Rectangle__height'

- we are getting this error because '__width' & '__height' we defined as private variables in superclass
which will not be accessed in subclasses as they are private for superclass
- in order to access those private variables of superclass in subclasses we use get and set methods

In [394]:
class Polygon:
    __width = None  # we are using '__' to make vaibales as private
    __height = None
    
    def set_vlaues(self, width, height):
        self.__width = width
        self.__height = height
     
    def get_width(self):   #get_width & get_height are public methods we can use anywhere inside class
        return self.__width
    
    def get_height(self):
        return self.__height
    
class Rectangle(Polygon):
    def area(self):
        return self.get_height() * self.get_width()
    
class Triangle(Polygon):
    def area(self):
        return self.get_height() * self.get_width() /2       
    
# Polygon = superclass 
# Rectangle & Triangle = subclasses
# we ae inheriting properties from Polygon to subclasses

rect = Rectangle()   # Created rectangle instance
tri = Triangle()    # cteated triangle instance

rect.set_vlaues(10, 20)
tri.set_vlaues(10,20)

print(rect.area())
print(tri.area())

200
100.0


In [397]:
class Parent:
    def __init__(self):
        print('parent __init__')
        
class Child(Parent):     #Inheridted parent class
    def __init__(self):
        print('child __init__')
        
child = Child()    
# it will execute chlild class not parent class


child __init__


In [398]:
# Super function is alowes us to refer super class implicitly
# super function is a bult in function
class Parent:
    def __init__(selfn, name):
        print('parent __init__', name)
        
class Child(Parent):     #Inheridted parent class
    def __init__(self):
        print('child __init__')
        super().__init__('akshay')
        
child = Child()    
# we can see both child & super class

child __init__
parent __init__ akshay


In [400]:
print(Child.__mro__)
# mro standa for methos resolution order
# this will show the order which methos will be called 
# in general all the methos in child class will be ececuted first and then parent class will be executed if mentiones

(<class '__main__.Child'>, <class '__main__.Parent'>, <class 'object'>)


In [402]:
class Parent1:
    def __init__(selfn, name):
        print('parent1__init__', name)
        
class Parent2:
    def __init__(selfn, name):
        print('parent2__init__', name)        
        
class Child(Parent1, Parent2):     #Inheridted parent class
    def __init__(self):
        print('child__init__')
        super().__init__('akshay')
        
child = Child()    
# we can see both child & super class
print(Child.__mro__)

child__init__
parent1__init__ akshay
(<class '__main__.Child'>, <class '__main__.Parent1'>, <class '__main__.Parent2'>, <class 'object'>)


In [408]:
class Parent1:
    def __init__(selfn, name):
        print('parent1__init__', name)
        
class Parent2:
    def __init__(selfn, name):
        print('parent2__init__', name)        
        
class Child(Parent2, Parent1):     #Inheridted parent class   # also it will ececute in order which we parent class are mentioned. Parent 2 will be excuted firest then Parent
    def __init__(self):
        print('child__init__')
        Parent2.__init__(self, 'akshay')
        Parent1.__init__(self, 'mayur')
        
child = Child()    
# we can see both child & super class
print(Child.__mro__)

child__init__
parent2__init__ akshay
parent1__init__ mayur
(<class '__main__.Child'>, <class '__main__.Parent2'>, <class '__main__.Parent1'>, <class 'object'>)


# Exceptions

try and except clause:-
> In Python, try-except clauses handle the exceptions. try clause is executed first, if an exception occurs the rest of try clause is skipped and except clause is executed; if no exception occurs, the except clause is skipped.

> It is important to note that SyntaxErrors are not handled by these clauses.
> It is also possible to handle selected exceptions only, if you type the name of that exception after except clause.
If no particular exception is mentioned then except clause is executed for all exceptions caught in try block. 

In [29]:
try:
    file = open('C:/Users/Adinath/Desktop/Data_Science/akshay.txt', 'w') #When use 'r' then we get exception as we are writing in readi only file 
    file.write('my name is akshay')
except IOError:
    print ("Error: cant find file or read data")   
else:
     print ("Written content in the file successfully") 
     file.close

Written content in the file successfully


In [12]:
try:
    32/0
except:
    print('Dividing By zeror')

Dividing By zeror


In [25]:
try:
    car_brands= ['ford', 'ferrari', 'bmw']
    print(car_brands[3]) 
except IndexError:
    print('There is no such index!')

There is no such index!


In [22]:
try:
    print('My Model')
except(TypeError, IndexError, NameError, ZerorDivisionError):
    print('My Exceptions')

My Model


In [21]:
my_variable = 'My variable'
try:
    print(my_variable) 
except NameError:
    print('NameError caught!') 
else:
    print('No NameError')

My variable
No NameError


In [28]:
try:
    raise IndexError('This index is not allowed')
except:
    print('Doing something with the exception!')
    raise

Doing something with the exception!


IndexError: This index is not allowed

In [29]:
try:
    print(my_variable) 
except NameError:
    print('Except block') 
finally:
    print('Finally block')

My variable
Finally block


In [47]:
car_list = ['tata', 'zen', 'benz']
message = 'My first car is'  + car_list[0].title()
print(message)


My first car isTata


In [57]:
car_list.insert(0, 'nexa')
print(car_list)
print(car_list[1])

['nexa', 'nexa', 'nexa', 'nexa', 'tata', 'zen', 'benz', 'hudai', 'hudai', 'hudai', 'hudai']
nexa


In [107]:
car_list.reverse()

In [115]:
print(car_list)

['zen', 'maruti', 'benz', 'Hero', 'BMW']


In [123]:
for list in car_list:
    print(list[0],list[1])

z e
m a
b e
H e
B M


In [153]:
squares = [] #Initialising emty List
for i in range(0,11):
    squares.append(i*2)
print(squares)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [154]:
#OR
squares = [] #Initialising emty List
for i in range(0,11):
    values = i*2
    squares.append(values)
print(squares)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [155]:
#OR
squares = [i*2 for i in range(0,11)]
print(squares)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [170]:
print(squares[0])
print(squares[0:])
print(squares[:])
print(squares[5:])
print(squares[1:5])
print(squares[-5:])
print(squares[:-5])

0
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[10, 12, 14, 16, 18, 20]
[2, 4, 6, 8]
[12, 14, 16, 18, 20]
[0, 2, 4, 6, 8, 10]


In [172]:
#Copying a list
list1 = ['hcl', 'amzon','microsoft','google']
print(list1)
list2 = list1[:]
print(list2)

['hcl', 'amzon', 'microsoft', 'google']
['hcl', 'amzon', 'microsoft', 'google']


In [180]:
tuple1 = ('hcl', 'amzon','microsoft','google')
print(tuple1)
print(tuple1[0])
print(tuple1[0:])

('hcl', 'amzon', 'microsoft', 'google')
hcl
('hcl', 'amzon', 'microsoft', 'google')


In [183]:
#We cannot update tuple
tuple1[0] = 'APPLE'
tuple1[0] = 'APPLE'

TypeError: 'tuple' object does not support item assignment

In [ ]:
# '=' & '==' Operator
car = 'bmw'  #sets the value of car to 'bmw'
car == 'bmw' #This equality operator returns True if the values on the left and right side of the operator match False if they don’t match

In [199]:
number = input('enter number to find calculation')
number1 = int(input('enter number to find calculation'))

enter number to find calculation'10'
enter number to find calculation11


In [200]:
print(number)
print(number1)
print(type(number))
print(type(number1))

'10'
11
<class 'str'>
<class 'int'>


In [1]:
#Letting the User Choose When to Quit 
prompt = "\nTell me something, and I will repeat it back to you:"
prompt += "\nEnter 'quit' to end the program. "
message = ""
while message != 'quit':
    message = input(prompt)
    print(message)


Tell me something, and I will repeat it back to you:
Enter 'quit' to end the program. hello
hello

Tell me something, and I will repeat it back to you:
Enter 'quit' to end the program. quit
quit


In [6]:
prompt = "\nTell me something, and I will repeat it back to you:" 
prompt += "\nEnter 'quit' to end the program. "
active = True
while active:
    message = input(prompt)
    
    if message == 'quit':
        active = False
    else:
        print(message)


Tell me something, and I will repeat it back to you:
Enter 'quit' to end the program. hello
hello

Tell me something, and I will repeat it back to you:
Enter 'quit' to end the program. quit


In [2]:
#Using break to Exit a Loop 
prompt = "\n Enter the name of city you have visited"
prompt += "\n Enter quit when you finished"

while True:
    city = input(prompt)
    
    if city == 'quit':
        break
    else:
         print("I'd love to go to " + city.title() + "!")    


 Enter the name of city you have visited
 Enter quit when you finished11
I'd love to go to 11!

 Enter the name of city you have visited
 Enter quit when you finishedquit


In [1]:
#passing list to  function paramter
def greet_users(names):
    """Print a simple greeting to each user in the list.""" 
    for name in names:
        msg = "Hello, " + name.title() + "!"
        print(msg)
usernames = ['hannah', 'ty', 'margot']
greet_users(usernames)

Hello, Hannah!
Hello, Ty!
Hello, Margot!


Differnce Between Python 2 & Python 3
1. The print Function 
    #print "Hello World" #is acceptable in Python 2 
    print ("Hello World") # in Python 3, print must be followed by () 
    
2. #print hi,           # Trailing comma suppresses newline in Python 2 
    print('hi', end=" ")  # Appends a space instead of a newline in Python  
    
3. Reading Input from Keboard
        # Python 2 has two versions of input functions, input() and raw_input(). The input() function treats the received data         as string if it is included in quotes '' or "", otherwise the data is treated as number. 
        In Python 3, raw_input() function is deprecated. Further, the received data is always treated as string.     
     
4. #Integer Division 
        #In Python 2, the result of division of two integers is rounded to the nearest integer. As a result, 3/2 will show 1.           In order to obtain a floating-point division, numerator or denominator must be explicitly used as float. Hence, either         3.0/2 or 3/2.0 or 3.0/2.0 will result 
        #in 1.5 Python 3 evaluates 3 / 2 as 1.5 by default, which is more intuitive for new programmers.  

5. xrange() Function Removed In Python 2 range() returns a list, and xrange() returns an object that will only generate the            items in the range when needed, saving memory. 
       In Python 3, the range() function is removed, and xrange() has been renamed as range(). In addition, the range() object        supports slicing in Python 3.2 and later .

### Placeholder formatting
Also known as Old string formatting uses modulo operator (%) to inject different types of variables.
Operator   Data type         
%s   string
%d   integer
%f    floating point number

In [1]:
who = "You" 
print ('Remember why %s started' %who) 

Remember why You started


In [5]:
pi = 3.141592
print('pi, %f is not equal to 22/7' %pi)

pi, 3.141592 is not equal to 22/7


In [10]:
print('python %d is awesome' %3)
print('%s to %s' %('Alledic', 'Morning'))
print(' My name is %s i am %d old' %('Akshay', 25))

python 3 is awesome
Alledic to Morning
 My name is Akshay i am 25 old


In [11]:
pi = 3.141592653589793 
print ("value of pi: %1.3f" %pi) 
print ("value of pi: %10.4f" %pi) 

value of pi: 3.142
value of pi:     3.1416


## String format() method

In [12]:
who = "Me" 
print ('Hear {} Roar' .format(who))
print ("{} is the {}" .format ("Ours", "Fury")) 

Hear Me Roar
Ours is the Fury


In [15]:
print ("{} is composed of {}" .format("Forever", "nows")) 
print ("{1} is composed of {0}" .format("Forever", "nows"))  
print ("{} wakes up the {} cells" .format('Nonsense', 'Brain'))
print ("{b} wakes up the {n} cells" .format(n='Nonsense', b='Brain')) 
print ("{pi: 1.6f}" .format (pi=3.1415926535)) 
print ("{0:6}{1:6}{2:7}{3:7}" .format ("This", "text", "looks", "great"))
print ("{0:6}{1:6}{1:7}{3:7}" .format ("This", "text", "looks", "great")) 

Forever is composed of nows
nows is composed of Forever
Nonsense wakes up the Brain cells
Brain wakes up the Nonsense cells
 3.141593
This  text  looks  great  
This  text  text   great  


##  f strings

In [19]:
x = 'Blessed'
y = 'Obsessed'
z = f'Stressed, {x} and Python {y}'
print(z)
print (f'Stressed, {x} and Python {y}')
print ('Stressed, {} and Python {}' .format(x, y)) 
print ('Stressed, %s and Python %s' %(x, y)) 

Stressed, Blessed and Python Obsessed
Stressed, Blessed and Python Obsessed
Stressed, Blessed and Python Obsessed
Stressed, Blessed and Python Obsessed


## Indexing and slicing

In [24]:
a = 'Stay trippy little hippie' 
print(a[3:9]) 
print(a[3:9:2])
print(a[3:9:3]) 
message = "Lxoesit   Umnoiscxozren" 
print(len(message))
print(message [0:23:2])

y trip
yti
yr
23
Lost Unicorn


In [29]:
text = 'Cruising the waves'
print(text [:])      #grabs everything 
print(text [::1])
print(text [::2])
print(text [::-1])   #trick to reverse a string 

Cruising the waves
Cruising the waves
Cusn h ae
sevaw eht gnisiurC


# Strings are immutable
Python strings have a special property of immutability i.e., once a string is created, the characters within it can’t be changed or replaced. Therefore, assigning values to an indexed position in the string results in an error.

In [30]:
x = 'Cue the Confetti' 
x[5] = 'z' 

TypeError: 'str' object does not support item assignment

## str.capitalize ()

In [35]:
print('hypermnesia'.capitalize ())

Hypermnesia


In [36]:
greyjoy = 'wE dO nOt sOw' 
print(greyjoy.capitalize ())

We do not sow


## str.title ()
It returns a titlecased copy of string i.e., first character of each word is uppercased and the remaining characters are lowercased.

In [37]:
'valar morghulis'.title () 

'Valar Morghulis'

In [38]:
bran = 'three-eyed raven'.title() 
print (bran)

Three-Eyed Raven


##  str.index (substring)
 It returns the index of first instance of substring or character, passed to it.

In [41]:
x = 'Mess with North, leave in hearse!' 
print(x.index ('s'))
print(x.index ('orth'))

2
11


## str.lower () 
It returns a lowercased copy of string.

In [42]:
print('sElcOUth'.lower())

selcouth


## str.replace(old, new)
It returns a copy of the string with all occurrences of substring, old replaced by new.

In [49]:
print('akshay'.replace('ay', 'zz'))
print('North'.replace('th', 'way'))
x = 'Pele'
print(x.replace('e', 'o'))

akshzz
Norway
Polo


## str.upper() 
It returns an uppercased copy of string.

In [51]:
print('akshayu'.upper())

AKSHAYU


### NUMPY

Numpy  array is python list along with some added features. 

In [270]:
import numpy as np
a = np.array([1,2,3]) #One dimentional array
print(a)

[1 2 3]


In [299]:
import numpy as np
b = np.array([[1,2,3], [4,5,6]])   #Two dimentional array
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [298]:
#Numpy array can be mutable(editable) as we creating on list
b[1] = 7
b

array([5.        , 7.        , 5.22222222, 5.33333333, 5.44444444,
       5.55555556, 5.66666667, 5.77777778, 5.88888889, 6.        ])

In [297]:
b[1,1] = 8
print(b)
print(b[:0])
print(b[0:])
print(b[1:])

IndexError: too many indices for array

Initializing numpy array

In [281]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [285]:
#np.arange(startnumber, endnumber, interval)
np.arange(10,25,5)

array([10, 15, 20])

In [286]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

Arranging N numbers between X & Y

In [295]:
#np.linspace(startnumber, endnumber, noofpoints)
b = np.linspace(5,6,10)
print(b)
print(b.shape)

[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]
(10,)


In [289]:
c = np.linspace(5,10,6)
print(c)

[ 5.  6.  7.  8.  9. 10.]


In [ ]:
c = np.linspace(5,10,6)
print(c)

filling same numbers in a array of dimension X, Y

In [290]:
np.full((2,2), 5)

array([[5, 5],
       [5, 5]])

In [291]:
np.full((2,4), 6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

filling random numbers in a array of dimension X,y

In [9]:
import numpy as np
d = np.random.random((2,2))
print(d)
print(d.shape)
print(d.ndim)   #It returns the dimensions
print(d.dtype)  #Returs data type of elements in array,
#NOTE: Numpy array contains data of homogeneous types.
print(d.size)   #total number of elemnts

[[0.10914595 0.83006587]
 [0.22675197 0.24224989]]
(2, 2)
2
float64
4


Maths using Numpy

In [14]:
np.sum([10,20])

30

In [17]:
a, b = 10,20
e = np.sum([a,b])
print(e)

30


In [18]:
'''np.sustract(a,b)
np.divide(a,b)
np.multiply(a,b)
np.exp(a)
np.sqrt(a)
np.sin(a)
np.cos(a)'''

'np.sustract(a,b)\nnp.divide(a,b)\nnp.multiply(a,b)\nnp.exp(a)\nnp.sqrt(a)\nnp.sin(a)\nnp.cos(a)'

Array broadcasting

In [25]:
a = np.array([[0,0,0], [10,10,10], [20,20,20], [30,30,30]])
b = np.array([0,1,2])
print('first array a is :\n', a, '\n')
print('Second array b is :\n', b, '\n')
print('sum of arrays a&b is:\n', a+b)

first array a is :
 [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 

Second array b is :
 [0 1 2] 

sum of arrays a&b is:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


### NLTK(Natural Language Tool Kit)

In [103]:
import nltk
#To install all corpuses present in NLTK
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [107]:
from nltk.corpus import names
names.words()

LookupError: 
**********************************************************************
  Resource names not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('names')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/names

  Searched in:
    - 'C:\\Users\\Adinath/nltk_data'
    - 'C:\\Users\\Adinath\\Anaconda3\\nltk_data'
    - 'C:\\Users\\Adinath\\Anaconda3\\share\\nltk_data'
    - 'C:\\Users\\Adinath\\Anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\Adinath\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************
